### ISSUE TITLE
Add tools like esri-loader, esri-loader-hooks, react-arcgis?

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/awesome-arcgis-developer#25]
Not sure if they fit the scope of this repo, but seems like these tools are very useful for working with the JS API:
-  https://github.com/Esri/react-arcgis
-  https://github.com/Esri/esri-loader
- https://github.com/tomwayson/esri-loader-hooks 

cc @patrickarlt @araedavis

**Comment by hhkaos** [comment]
It make total sense to me, where would you place them? under [#Helpers](https://github.com/Esri/awesome-arcgis-developer#helpers) ?

**Comment by tomwayson** [comment]
I can make a PR to add those under [Helpers](https://github.com/Esri/awesome-arcgis-developer#helpers).

I'd also propose adding the [esri-loader Examples](https://github.com/Esri/esri-loader/#examples) under [Code Samples and Snippets](https://github.com/Esri/awesome-arcgis-developer#code-samples-and-snippets).

**Comment by hhkaos** [comment]
Awesome @tomwayson, that sounds great to me!
