### ISSUE TITLE
Add social preview image

### ISSUE THREAD

**Issue by hhkaos** [Esri/awesome-arcgis-developer#27]
It would be nice to have an image for social sharing, can you help me with this @jf990 ?

<img width="647" alt="Screenshot 2021-08-31 at 08 18 49" src="https://user-images.githubusercontent.com/826965/131451999-73fb1626-fb32-45fb-bdd9-52a6c6074ed3.png">

**Comment by jf990** [comment]
@hhkaos 

![social-image-1280x640](https://user-images.githubusercontent.com/13524488/131588553-cfa1c728-af26-4cb9-9b8d-701398656c8b.png)

**Comment by hhkaos** [comment]
What do you think about this one, to increase the CTA?

![social-share-with-text](https://user-images.githubusercontent.com/826965/131648839-8f8be4f1-c4a5-4bc4-88ff-d18f8ba61a1b.png)
